Fix for worker node name has some limitation
When I named worker node as worker-0, it failed when I unlock
worker node.
We can find root cause
File "/usr/lib64/python2.7/site-packages/sysinv/common/ceph.py",
line 559, in update_crushmap
    storage_num = int(hostupdate.ihost_orig['hostname'][8:])
ValueError: invalid literal for int() with base 10: ''

Test pass with this fix for worker-0 unlock test.

Change-Id: I01865d43f4456de81d72689f799441531a444be2
Closes-Bug: #1820810
Signed-off-by: zhipengl <zhipengs.liu@intel.com>